language: php

sudo: required

matrix:
  include:
    - php: 7.2
      env: SW_VERSION="4.5.2"
    - php: 7.3
      env: SW_VERSION="4.5.2"
    - php: 7.4
      env: SW_VERSION="4.5.2"

services:
  - mongodb

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR
  - eval "$(gimme 1.13.1)"
  - go version

install:
  - cd $TRAVIS_BUILD_DIR
  - bash ./tests/swoole.install.sh
  - pecl install mongodb
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add ./tests/ci.ini


before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer config -g process-timeout 900 && composer update

script:
  - composer analyse
  - composer test
  - composer test-go
